version: '3'

networks:
  myNet:
    driver: bridge

services:
  node:
    networks:
    - myNet
    restart: always
    build: .
    ports:
      - 3001:3000
  mongo:
    image: mongo
    networks:
    - myNet
    restart: always
    ports:
      - 27017:27017